apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telecom-cloud-platform.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "telecom-cloud-platform.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "telecom-cloud-platform.fullname" . }}
    spec:
      containers:
        - name: telecom-cloud-platform
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
