name: Telecom Cloud Platform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest -v backend/tests


  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: image
        run: |
          echo "tag=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: |
          docker build \
            -t philiphabib/telecom-cloud-platform:${{ steps.image.outputs.tag }} \
            .

      - name: Push Docker image
        run: |
          docker push \
            philiphabib/telecom-cloud-platform:${{ steps.image.outputs.tag }}


  update-helm:
    name: Update Helm Image Tag
    runs-on: ubuntu-latest
    needs: docker

    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Update Helm image tag
        run: |
          TAG="${GITHUB_SHA::7}"

          sed -i "s/^  tag:.*/  tag: ${TAG}/" \
            deploy/helm/telecom-cloud-platform/values.yaml

          echo "Updated Helm image tag to: ${TAG}"

          grep -n -A4 "^image:" \
            deploy/helm/telecom-cloud-platform/values.yaml

      - name: Commit Helm update
        run: |
          TAG="${GITHUB_SHA::7}"

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add deploy/helm/telecom-cloud-platform/values.yaml

          git diff --cached --quiet && \
            echo "No Helm changes to commit." && exit 0

          git commit -m "Update Telecom Cloud Platform image to ${TAG}"
          git push
